##################################################################################
# Database configuration
# Connecting string is in Go pq driver format:
# host=<host> port=<port> user=<databaseName>
[database]
connecting_string = "host=localhost port=5432 user=postgres password=fentezi dbname=runners_db sslmode=disable"
max_idle_connection = 5
max_open_connection = 20
connection_max_lifetime = "60s"
driver_name = "postgres"
##################################################################################
# HTTP server configuration
[http]
server_address = ":8080"
##################################################################################